[package]
name = "librarytest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "librarytest"
crate_type = ["cdylib"]

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]
